import "../styles/globals.css"

import Header from "./components/Header"

import head from "./head"

// import Head from "./head"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
      </body>
    </html>
  )
}
